## Model Building

## Prepare Dataset for Modelling

In [2]:
love_island_data = pd.read_csv('outputs/love_island_data.csv')
print("'love_island_data' successfully loaded...")

'love_island_data' successfully loaded...

In [3]:
import pandas as pd
import numpy as np
import os
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.options.display.max_colwidth = None
pd.set_option("display.float_format", lambda x: '%.2f' % x)

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [4]:
love_island_data.shape

(2998, 11)

In [5]:
love_island_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2998 entries, 0 to 2997
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0.1                    2998 non-null   int64
 1   Unnamed: 0                      2998 non-null   int64
 2   author.properties.friends       2998 non-null   int64
 3   author.properties.status_count  2998 non-null   float64
 4   author.properties.verified      2998 non-null   bool
 5   content.body                    2998 non-null   object
 6   location.country                2998 non-null   object
 7   properties.platform             2998 non-null   object
 8   properties.sentiment            2998 non-null   float64
 9   location.latitude               2998 non-null   float64
 10  location.longitude              2998 non-null   float64
dtypes: bool(1), float64(4), int64(3), object(3)
memory usage: 237.3+ KB

In [6]:
# Drop duplicate and irrelevant columns in dataframe
del love_island_data['Unnamed: 0.1']
del love_island_data ['Unnamed: 0']

In [7]:
love_island_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2998 entries, 0 to 2997
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   author.properties.friends       2998 non-null   int64
 1   author.properties.status_count  2998 non-null   float64
 2   author.properties.verified      2998 non-null   bool
 3   content.body                    2998 non-null   object
 4   location.country                2998 non-null   object
 5   properties.platform             2998 non-null   object
 6   properties.sentiment            2998 non-null   float64
 7   location.latitude               2998 non-null   float64
 8   location.longitude              2998 non-null   float64
dtypes: bool(1), float64(4), int64(1), object(3)
memory usage: 190.4+ KB

In [8]:
love_island_data.head()

,author.properties.friends,author.properties.status_count,author.properties.verified,content.body,location.country,properties.platform,properties.sentiment,location.latitude,location.longitude
0,1689,22566.00,False,Can't believe I'm missing Love Island ðŸ˜©,GB,twitter,1.00,51.57,0.46
1,114,1377.00,False,Last tweet about future wedding..... if I actually want a wedding I actually need to find a guy XD we all know I'm a loner. unlovable,GB,twitter,1.00,52.97,-1.17
2,568,8375.00,False,"How many times does he wonna say the phrase ""i deal with shit"" #LoveIsland",GB,twitter,-1.00,51.39,0.03
3,1845,19394.00,False,...even better if time travel were invented and I could go there back in 1876 and have a whiskey with Al #Deadwood,GB,twitter,-1.00,51.65,-3.80
4,1617,17922.00,False,@GreenAlty @ShakeyStephens My Mum in mid 80s pushed into road by Black migrants 2 sons with disabilities attacked robbed U THINK WE NEED MOR,GB,twitter,0.00,53.54,-2.65

## Train_Test_Split

In [9]:
# 0.3, 0.7

In [10]:
from sklearn.model_selection import train_test_split
from autogluon.tabular import TabularDataset, TabularPredictor

In [11]:
# y = mX + c

In [12]:
X = love_island_data[["author.properties.friends",
                    "author.properties.status_count",
                    "author.properties.verified","content.body",
                    "location.country","properties.platform",
                    "properties.sentiment","location.latitude",
                    "location.longitude"]]

In [13]:
type(X)

pandas.core.frame.DataFrame

In [14]:
X.head()

,author.properties.friends,author.properties.status_count,author.properties.verified,content.body,location.country,properties.platform,properties.sentiment,location.latitude,location.longitude
0,1689,22566.00,False,Can't believe I'm missing Love Island ðŸ˜©,GB,twitter,1.00,51.57,0.46
1,114,1377.00,False,Last tweet about future wedding..... if I actually want a wedding I actually need to find a guy XD we all know I'm a loner. unlovable,GB,twitter,1.00,52.97,-1.17
2,568,8375.00,False,"How many times does he wonna say the phrase ""i deal with shit"" #LoveIsland",GB,twitter,-1.00,51.39,0.03
3,1845,19394.00,False,...even better if time travel were invented and I could go there back in 1876 and have a whiskey with Al #Deadwood,GB,twitter,-1.00,51.65,-3.80
4,1617,17922.00,False,@GreenAlty @ShakeyStephens My Mum in mid 80s pushed into road by Black migrants 2 sons with disabilities attacked robbed U THINK WE NEED MOR,GB,twitter,0.00,53.54,-2.65

In [15]:
y = love_island_data["properties.sentiment"]

In [16]:
type(y)

pandas.core.series.Series

In [17]:
y.head()

0    1.00
1    1.00
2   -1.00
3   -1.00
4    0.00
Name: properties.sentiment, dtype: float64

In [18]:
train_data, test_data = train_test_split(love_island_data,test_size = 0.30, random_state =42)

In [35]:
train_data.shape, test_data.shape

((2098, 9), (900, 9))

In [37]:
train_data.head(3)

,author.properties.friends,author.properties.status_count,author.properties.verified,content.body,location.country,properties.platform,properties.sentiment,location.latitude,location.longitude
858,2723,27039.00,False,Ain't gna stress it anymoreðŸ˜´,GB,twitter,-1.00,51.45,-0.98
1011,278,31474.00,False,@Wackkyyy Yes if you take your shirt off like you did in the skype call. ðŸ‘€,GB,twitter,-1.00,51.60,-0.34
48,422,1083.00,False,New Music Alert https://t.co/nDKbwFcD7d,GB,twitter,1.00,51.51,-0.12

In [38]:
test_data.head(3)

,author.properties.friends,author.properties.status_count,author.properties.verified,content.body,location.country,properties.platform,properties.sentiment,location.latitude,location.longitude
1376,282,2085.00,False,@Donforester Many established 1st generation immigrants want to restrict immigration. Many 2nd generation eg Irish more welcoming,GB,twitter,0.00,53.42,-2.92
932,51,12533.00,False,@smollyalexander thank u hunty,GB,twitter,1.00,53.37,-2.17
144,931,307.00,False,Hedge removal part one...!! @ Dalkeith https://t.co/slEBFhE0w9,GB,twitter,-1.00,55.87,-3.07

## basic model build

In [42]:
label = 'properties.sentiment'

In [43]:
%%time

save_path = 'models'
predictor = TabularPredictor(label=label, path=save_path).fit(train_data)

Warning: path already exists! This predictor may overwrite an existing predictor! path="models"
Beginning AutoGluon training ...
AutoGluon will save models to "models/"
AutoGluon Version:  0.7.0
Python Version:     3.9.16
Operating System:   Darwin
Platform Machine:   x86_64
Platform Version:   Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64
Train Data Rows:    2098
Train Data Columns: 8
Label Column: properties.sentiment
Preprocessing data ...
AutoGluon infers your prediction problem is: 'multiclass' (because dtype of label-column == float, but few unique label-values observed and label-values can be converted to int).
	3 unique label values:  [-1.0, 1.0, 0.0]
	If 'multiclass' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5044.63 MB
	Train Data (Original)  Memory Usage: 0.72 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['content.body']
			CountVectorizer fit with vocabulary size = 87
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Useless Original Features (Count: 1): ['properties.platform']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('bool', [])         : 1 | ['author.properties.verified']
		('float', [])        : 3 | ['author.properties.status_count', 'location.latitude', 'location.longitude']
		('int', [])          : 1 | ['author.properties.friends']
		('object', [])       : 1 | ['location.country']
		('object', ['text']) : 1 | ['content.body']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  1 | ['location.country']
		('float', [])                       :  3 | ['author.properties.status_count', 'location.latitude', 'location.longitude']
		('int', [])                         :  1 | ['author.properties.friends']
		('int', ['binned', 'text_special']) : 26 | ['content.body.char_count', 'content.body.word_count', 'content.body.capital_ratio', 'content.body.lower_ratio', 'content.body.digit_ratio', ...]
		('int', ['bool'])                   :  1 | ['author.properties.verified']
		('int', ['text_ngram'])             : 88 | ['__nlp__.about', '__nlp__.all', '__nlp__.am', '__nlp__.an', '__nlp__.and', ...]
	1.9s = Fit runtime
	7 features in original data used to generate 120 features in processed data.
	Train Data (Processed) Memory Usage: 0.5 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 2.22s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 1678, Val Rows: 420
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.4667	 = Validation score   (accuracy)
	9.06s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.4238	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.6238	 = Validation score   (accuracy)
	6.76s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMXT ...
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/hackermanproject_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/hackermanproject_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: LightGBM ...
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/hackermanproject_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/hackermanproject_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: RandomForestGini ...
	0.6452	 = Validation score   (accuracy)
	2.69s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.6381	 = Validation score   (accuracy)
	1.55s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: CatBoost ...
	0.6714	 = Validation score   (accuracy)
	8.11s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.6333	 = Validation score   (accuracy)
	1.11s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.6167	 = Validation score   (accuracy)
	1.17s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost ...
	0.6524	 = Validation score   (accuracy)
	2.17s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.5976	 = Validation score   (accuracy)
	5.38s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. If you are using Mac OSX, Please try 'brew install libomp'. Detailed info: dlopen(/Users/macbook/opt/anaconda3/envs/hackermanproject_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/macbook/opt/anaconda3/envs/hackermanproject_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
Fitting model: WeightedEnsemble_L2 ...
	0.6714	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 43.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("models/")

CPU times: user 39.8 s, sys: 3 s, total: 42.8 s
Wall time: 43.2 s

In [44]:
predictor.leaderboard(silent=True)

,model,score_val,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost,0.67,0.01,8.11,0.01,8.11,1,True,6
1,WeightedEnsemble_L2,0.67,0.01,8.86,0.00,0.75,2,True,11
2,XGBoost,0.65,0.02,2.17,0.02,2.17,1,True,9
3,RandomForestGini,0.65,0.08,2.69,0.08,2.69,1,True,4
4,RandomForestEntr,0.64,0.14,1.55,0.14,1.55,1,True,5
5,ExtraTreesGini,0.63,0.08,1.11,0.08,1.11,1,True,7
6,NeuralNetFastAI,0.62,0.02,6.76,0.02,6.76,1,True,3
7,ExtraTreesEntr,0.62,0.10,1.17,0.10,1.17,1,True,8
8,NeuralNetTorch,0.60,0.04,5.38,0.04,5.38,1,True,10
9,KNeighborsUnif,0.47,0.12,9.06,0.12,9.06,1,True,1
10,KNeighborsDist,0.42,0.02,0.03,0.02,0.03,1,True,2

## Model Evaluation

load test data to make predictions

In [45]:
y_test = test_data[label]

In [46]:
y_test.head()

1376    0.00
932     1.00
144    -1.00
1752    1.00
51     -1.00
Name: properties.sentiment, dtype: float64

In [47]:
y_test = test_data[label]  # values to predict

In [48]:
y_test [0:5]

1376    0.00
932     1.00
144    -1.00
1752    1.00
51     -1.00
Name: properties.sentiment, dtype: float64

In [49]:
test_data_nolab = test_data.drop(columns=[label])  # delete label column to avoid cheating

In [51]:
test_data_nolab.head()

,author.properties.friends,author.properties.status_count,author.properties.verified,content.body,location.country,properties.platform,location.latitude,location.longitude
1376,282,2085.00,False,@Donforester Many established 1st generation immigrants want to restrict immigration. Many 2nd generation eg Irish more welcoming,GB,twitter,53.42,-2.92
932,51,12533.00,False,@smollyalexander thank u hunty,GB,twitter,53.37,-2.17
144,931,307.00,False,Hedge removal part one...!! @ Dalkeith https://t.co/slEBFhE0w9,GB,twitter,55.87,-3.07
1752,291,1580.00,False,God I love @KevinHart4real ðŸ˜‚ snapchats making my night,GB,twitter,51.42,-0.45
51,680,3691.00,False,@MargevonMarge Blimey. You still haven't served enough time here? #EUref #Remain,GB,twitter,53.55,-0.66

In [52]:
save_path

'models'

In [53]:
predictor

In [55]:
save_model_predictor = TabularPredictor.load(save_path)

In [58]:
save_model_predictor

In [59]:
y_pred = save_model_predictor.predict(test_data_nolab)

In [60]:
y_pred[0:5]

1376   -1.00
932    -1.00
144    -1.00
1752    1.00
51     -1.00
Name: properties.sentiment, dtype: float64

In [61]:
print("Predictions:  \n", y_pred)
perf = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)

Evaluation: accuracy on test data: 0.6244444444444445
Evaluations on test data:
{
    "accuracy": 0.6244444444444445,
    "balanced_accuracy": 0.5698524240516779,
    "mcc": 0.3923485132664916
}

Predictions:
 1376   -1.00
932    -1.00
144    -1.00
1752    1.00
51     -1.00
414    -1.00
2529   -1.00
266     0.00
2704   -1.00
2423    0.00
1849    0.00
416    -1.00
2859   -1.00
2710   -1.00
1041   -1.00
2894    0.00
2064   -1.00
460    -1.00
2354   -1.00
2920   -1.00
1507   -1.00
761    -1.00
102    -1.00
1812    1.00
44      0.00
1488   -1.00
291    -1.00
2468   -1.00
2131   -1.00
52     -1.00
506     0.00
289    -1.00
174     1.00
1047   -1.00
2812    0.00
2967   -1.00
2881   -1.00
1114   -1.00
1480   -1.00
1229   -1.00
564    -1.00
298     1.00
2735    0.00
678     0.00
194     0.00
1239   -1.00
63     -1.00
765    -1.00
1737   -1.00
393    -1.00
1211    1.00
1791    0.00
2247    0.00
565     1.00
1725    0.00
1825    0.00
1691    0.00
1511   -1.00
332    -1.00
1882   -1.00
1260   -1.00
354    -1.00
1612    0.00
650    -1.00
744    -1.00
2417   -1.00
2757    1.00
2014    1.00
2661    1.00
246    -1.00
457    -1.00
1106   -1.00
2634    0.00
1269    1.00
511     0.00
2282   -1.00
2635   -1.00
693    -1.00
1717   -1.00
1286    0.00
450     1.00
2984   -1.00
1135    0.00
1756   -1.00
581    -1.00
998    -1.00
2898    0.00
1741   -1.00
331     0.00
1578   -1.00
45     -1.00
1956   -1.00
211     1.00
2252    0.00
178     0.00
2501   -1.00
1922   -1.00
93     -1.00
1446    1.00
1963    0.00
2030   -1.00
1544   -1.00
1091   -1.00
0       1.00
152     0.00
2860    0.00
2113    0.00
1435    1.00
755    -1.00
1746   -1.00
2093    0.00
940    -1.00
1406   -1.00
2841   -1.00
2577    0.00
2171   -1.00
1721   -1.00
1057   -1.00
2774    0.00
679    -1.00
2509   -1.00
527     0.00
2480   -1.00
2103    0.00
2233   -1.00
14      0.00
2452    0.00
1228   -1.00
2375   -1.00
2402    1.00
1798   -1.00
2648   -1.00
1988   -1.00
1553   -1.00
2208    0.00
1370   -1.00
978    -1.00
2784    0.00
368    -1.00
544    -1.00
2162    0.00
1089    1.00
1509    1.00
2470    0.00
798    -1.00
1102   -1.00
2275    0.00
1429    0.00
1688   -1.00
554     0.00
555    -1.00
2823    1.00
1950    1.00
1962    1.00
621     1.00
1814    0.00
1421   -1.00
2989    0.00
2005   -1.00
67      1.00
962    -1.00
727    -1.00
2629    1.00
2928   -1.00
1927   -1.00
1778   -1.00
2549   -1.00
2590   -1.00
911    -1.00
1195    0.00
1789    1.00
521    -1.00
1742   -1.00
2348   -1.00
343    -1.00
1961   -1.00
196     0.00
124    -1.00
184    -1.00
1913    0.00
2020    0.00
1730    0.00
2564   -1.00
1426   -1.00
408    -1.00
2412   -1.00
1762   -1.00
2599    1.00
254     0.00
2438    1.00
2885   -1.00
192     1.00
1073    0.00
557    -1.00
1945    0.00
789     1.00
840    -1.00
2132    0.00
2687   -1.00
495    -1.00
2016    0.00
2785    0.00
203     0.00
651    -1.00
819    -1.00
80      0.00
32     -1.00
1936    0.00
436     1.00
251    -1.00
718    -1.00
746     0.00
256    -1.00
1204   -1.00
2428    0.00
2813   -1.00
139     0.00
1726    0.00
2980   -1.00
88      1.00
1563   -1.00
2522    1.00
296     0.00
2025   -1.00
486     0.00
844    -1.00
599    -1.00
1596   -1.00
1461   -1.00
1391    0.00
1192    1.00
812     0.00
1253   -1.00
1100   -1.00
141    -1.00
1448    1.00
270    -1.00
1359   -1.00
2668    1.00
1467   -1.00
1090    0.00
2112    0.00
175     0.00
1018    0.00
736    -1.00
2754   -1.00
471    -1.00
1618    1.00
912     0.00
1357    0.00
2238    0.00
2284    0.00
705    -1.00
1642   -1.00
411     0.00
322     1.00
177     0.00
2555    0.00
598    -1.00
1626    0.00
2374   -1.00
1356    0.00
676    -1.00
535    -1.00
794     0.00
2953   -1.00
2266   -1.00
528    -1.00
1272    0.00
463     0.00
1061   -1.00
2066   -1.00
1662    0.00
162    -1.00
1494   -1.00
1468   -1.00
1566   -1.00
838    -1.00
2945    1.00
2289    1.00
30      0.00
1987    0.00
2845    0.00
2921    1.00
1839   -1.00
2457    0.00
2246   -1.00
2031   -1.00
864    -1.00
2525   -1.00
767    -1.00
2891   -1.00
479     0.00
1462   -1.00
1545    1.00
73     -1.00
1179   -1.00
1889    0.00
2732    0.00
1556   -1.00
1628   -1.00
1230    1.00
324    -1.00
2540   -1.00
1656   -1.00
2234   -1.00
1472   -1.00
2676   -1.00
1835    1.00
1525    0.00
1174    0.00
1621   -1.00
1510    1.00
601    -1.00
2095    0.00
1784   -1.00
321     0.00
2744   -1.00
239     0.00
1413   -1.00
969    -1.00
2994   -1.00
759     0.00
1125   -1.00
443    -1.00
1113   -1.00
2821    0.00
532    -1.00
1220    0.00
1161   -1.00
2421   -1.00
1694    1.00
889    -1.00
2610    0.00
605    -1.00
2469   -1.00
2657    1.00
572     1.00
1864    0.00
867    -1.00
691    -1.00
402    -1.00
439     0.00
2471   -1.00
108     0.00
2347   -1.00
2954   -1.00
318    -1.00
1032   -1.00
670    -1.00
1611    0.00
1023   -1.00
1405   -1.00
1580    0.00
1878    1.00
2149    0.00
879    -1.00
2638   -1.00
2503    0.00
2475   -1.00
433    -1.00
1271    0.00
423    -1.00
2663   -1.00
2750    0.00
2092    0.00
70     -1.00
729    -1.00
2392    0.00
1373    1.00
56      1.00
1598   -1.00
2955   -1.00
1457   -1.00
2950    0.00
642     0.00
309    -1.00
1925    0.00
2404   -1.00
2129    1.00
2643   -1.00
1601    1.00
1809   -1.00
1295   -1.00
1554   -1.00
432    -1.00
2944    0.00
1775    0.00
567     1.00
1703    0.00
1978   -1.00
2935   -1.00
1813   -1.00
2167    0.00
1764   -1.00
2839    0.00
1587    0.00
120     0.00
1398   -1.00
874     0.00
2487   -1.00
1497   -1.00
313     0.00
1475    0.00
233    -1.00
1644   -1.00
2722    0.00
1744   -1.00
111     0.00
1128    0.00
410     1.00
218     0.00
2887   -1.00
478    -1.00
1861   -1.00
2415   -1.00
2063   -1.00
1590   -1.00
485     0.00
2819    0.00
507     0.00
772    -1.00
387    -1.00
787    -1.00
543    -1.00
2875    0.00
2272   -1.00
1270   -1.00
2871    0.00
2045   -1.00
2712    0.00
135    -1.00
1221   -1.00
2304   -1.00
2809    1.00
2254    0.00
366     0.00
881     1.00
1159   -1.00
29     -1.00
2499    0.00
2043    0.00
1044    0.00
2907   -1.00
2204    1.00
2932   -1.00
183    -1.00
831     0.00
188     0.00
420    -1.00
170    -1.00
2698    0.00
43      0.00
87      1.00
1411    0.00
700     0.00
897    -1.00
282    -1.00
644    -1.00
1894    0.00
1980   -1.00
257    -1.00
2592   -1.00
1352   -1.00
930     0.00
1213   -1.00
1010   -1.00
2451   -1.00
149     1.00
1660    0.00
2356   -1.00
2390    0.00
1442    1.00
2111   -1.00
1078   -1.00
134     0.00
2745   -1.00
533    -1.00
847    -1.00
2783   -1.00
1084   -1.00
2370   -1.00
2569    0.00
2434   -1.00
2321    0.00
430     0.00
2189   -1.00
1740   -1.00
999    -1.00
1288    0.00
221    -1.00
1911    0.00
1983   -1.00
2715   -1.00
839     0.00
926    -1.00
2941    0.00
173    -1.00
1208    0.00
2330   -1.00
807     0.00
610    -1.00
2161   -1.00
2058   -1.00
756    -1.00
1374    0.00
964     1.00
472    -1.00
1732   -1.00
2223   -1.00
2546    0.00
314    -1.00
869    -1.00
602     0.00
1608   -1.00
272     0.00
2314    0.00
1748   -1.00
1025    0.00
1904    0.00
929     0.00
2791   -1.00
2313   -1.00
1261   -1.00
2591   -1.00
680     1.00
1097    0.00
1837   -1.00
1302   -1.00
168     0.00
903     1.00
2764    0.00
1207    0.00
1395   -1.00
1225   -1.00
2232   -1.00
1289   -1.00
367    -1.00
2273   -1.00
1117    0.00
1299    1.00
351     1.00
949    -1.00
1127    0.00
1099   -1.00
2756   -1.00
2624   -1.00
498    -1.00
2110   -1.00
210     0.00
2050   -1.00
900    -1.00
227    -1.00
365     0.00
1543   -1.00
2164    0.00
2771   -1.00
2927    0.00
2018   -1.00
407    -1.00
1916    0.00
2362   -1.00
2306    0.00
568     1.00
2405   -1.00
2008    0.00
7      -1.00
952    -1.00
1872    0.00
1075   -1.00
415    -1.00
741    -1.00
1034    0.00
2833   -1.00
199     0.00
283     0.00
231    -1.00
612    -1.00
2720    0.00
96     -1.00
1344   -1.00
2567    0.00
1920    0.00
1037    0.00
1071    0.00
829    -1.00
2861   -1.00
2585   -1.00
2380    0.00
1517   -1.00
104    -1.00
1847    0.00
594     0.00
2594   -1.00
842    -1.00
637    -1.00
695     0.00
226     1.00
2260   -1.00
1103   -1.00
1569    0.00
2228    0.00
2295    0.00
1800    0.00
1273   -1.00
1586   -1.00
464    -1.00
1575   -1.00
685    -1.00
1268   -1.00
805    -1.00
1577    1.00
2562   -1.00
212    -1.00
12      0.00
2902    0.00
422    -1.00
2211    0.00
1298    0.00
2637   -1.00
817    -1.00
2775    0.00
2917   -1.00
1591   -1.00
509     0.00
597    -1.00
2966    0.00
1583   -1.00
1343   -1.00
2641   -1.00
518    -1.00
1637    0.00
573    -1.00
2723   -1.00
1094    0.00
2115   -1.00
1134   -1.00
1417    1.00
1655    1.00
958    -1.00
2574   -1.00
2906   -1.00
358     0.00
1830   -1.00
1780   -1.00
2172    0.00
259    -1.00
2769    0.00
781    -1.00
2982    0.00
859     1.00
1027    0.00
2406    0.00
2086    0.00
2865   -1.00
764     1.00
2714   -1.00
2323   -1.00
456    -1.00
462    -1.00
2222    0.00
1053   -1.00
381     0.00
1412    0.00
2650    0.00
965     0.00
2303    1.00
2174   -1.00
1385    0.00
1149   -1.00
2309    0.00
1817   -1.00
2856   -1.00
1902   -1.00
1407   -1.00
2358   -1.00
2285    0.00
857    -1.00
1897    1.00
542     1.00
1965   -1.00
1670    0.00
2381   -1.00
2179   -1.00
1264   -1.00
2419   -1.00
845    -1.00
1340   -1.00
1361    1.00
2892    1.00
2178    0.00
2665   -1.00
2418   -1.00
1674   -1.00
1620    1.00
435    -1.00
2716   -1.00
237     1.00
2089    1.00
109    -1.00
2054    0.00
163     0.00
288     0.00
252     1.00
2079   -1.00
2741    0.00
2287   -1.00
2124    1.00
809    -1.00
2447   -1.00
2436   -1.00
2681   -1.00
2703    0.00
2616    1.00
1146   -1.00
2202    0.00
1017   -1.00
2398   -1.00
461     0.00
1565    0.00
1432    1.00
157    -1.00
1907    0.00
1614   -1.00
677     1.00
1675   -1.00
2357    0.00
238    -1.00
783    -1.00
1088    0.00
1971   -1.00
100    -1.00
315    -1.00
810    -1.00
1036   -1.00
1350    0.00
1187    0.00
261    -1.00
790    -1.00
1640    0.00
195    -1.00
1771    0.00
990     0.00
1731   -1.00
179    -1.00
2315   -1.00
340     1.00
1055   -1.00
2895    0.00
748    -1.00
1064    0.00
662    -1.00
480    -1.00
2136   -1.00
2701    0.00
1336   -1.00
2979    0.00
2046   -1.00
1241   -1.00
2706    0.00
742    -1.00
2413    0.00
1702    1.00
2335   -1.00
1739    1.00
1938    1.00
785    -1.00
2119    0.00
1600    0.00
247    -1.00
1503   -1.00
2836    0.00
2718   -1.00
626    -1.00
347    -1.00
278     0.00
1779    0.00
2848   -1.00
655     0.00
1210   -1.00
1868   -1.00
2622   -1.00
2586   -1.00
1410   -1.00
1706    0.00
942    -1.00
1559    0.00
445    -1.00
617    -1.00
2671    0.00
2515   -1.00
1436   -1.00
1123   -1.00
1558   -1.00
2550    0.00
547     1.00
1770   -1.00
2177   -1.00
263     0.00
2416    1.00
2351    0.00
1811   -1.00
353    -1.00
2997    1.00
208    -1.00
613     0.00
862     0.00
927     0.00
2805   -1.00
2666   -1.00
1747    0.00
1498   -1.00
57      0.00
2439   -1.00
811    -1.00
2190    0.00
561    -1.00
2044   -1.00
229    -1.00
2507   -1.00
1718   -1.00
2453    0.00
2258    0.00
1231   -1.00
1068   -1.00
2794    0.00
1518   -1.00
1564    0.00
707     0.00
424     0.00
69     -1.00
2779   -1.00
2437   -1.00
1684    0.00
2649    0.00
2970    1.00
2579   -1.00
1093   -1.00
1610    0.00
620     0.00
2340   -1.00
1729   -1.00
2466   -1.00
1029    0.00
1502   -1.00
1476    1.00
2527   -1.00
2040   -1.00
1392   -1.00
279     0.00
1533   -1.00
1651    1.00
2617   -1.00
907     0.00
2408   -1.00
553    -1.00
834     0.00
1105   -1.00
596    -1.00
2533   -1.00
802    -1.00
2987   -1.00
2983    0.00
2717   -1.00
440    -1.00
508     0.00
76      1.00
2959   -1.00
649     0.00
522     1.00
2889   -1.00
2535    0.00
1491    0.00
654     0.00
1173   -1.00
2225   -1.00
1190   -1.00
2721    0.00
630     0.00
1251   -1.00
2679   -1.00
945    -1.00
482    -1.00
2851    0.00
1110   -1.00
2561    0.00
2981    1.00
438    -1.00
1714   -1.00
1537    0.00
856     0.00
1979    0.00
166    -1.00
59      1.00
611    -1.00
530    -1.00
2707    0.00
49      0.00
2939    0.00
1005   -1.00
Name: properties.sentiment, dtype: float64

## Leaderboard

In [62]:
save_model_predictor.leaderboard(test_data, silent=True)

,model,score_test,score_val,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,ExtraTreesGini,0.64,0.63,0.24,0.08,1.11,0.24,0.08,1.11,1,True,7
1,RandomForestGini,0.63,0.65,0.21,0.08,2.69,0.21,0.08,2.69,1,True,4
2,ExtraTreesEntr,0.63,0.62,0.46,0.10,1.17,0.46,0.10,1.17,1,True,8
3,XGBoost,0.63,0.65,0.17,0.02,2.17,0.17,0.02,2.17,1,True,9
4,CatBoost,0.62,0.67,0.02,0.01,8.11,0.02,0.01,8.11,1,True,6
5,WeightedEnsemble_L2,0.62,0.67,0.03,0.01,8.86,0.01,0.00,0.75,2,True,11
6,RandomForestEntr,0.62,0.64,0.21,0.14,1.55,0.21,0.14,1.55,1,True,5
7,NeuralNetTorch,0.60,0.60,0.25,0.04,5.38,0.25,0.04,5.38,1,True,10
8,NeuralNetFastAI,0.58,0.62,0.04,0.02,6.76,0.04,0.02,6.76,1,True,3
9,KNeighborsUnif,0.44,0.47,0.03,0.12,9.06,0.03,0.12,9.06,1,True,1
10,KNeighborsDist,0.41,0.42,0.03,0.02,0.03,0.03,0.02,0.03,1,True,2

## Feature Importance

In [63]:
save_model_predictor.feature_importance(test_data, silent=True)

These features in provided data are not utilized by the predictor and will be ignored: ['properties.platform']

,importance,stddev,p_value,n,p99_high,p99_low
content.body,0.24,0.02,0.00,5,0.27,0.20
location.longitude,0.01,0.00,0.01,5,0.02,-0.00
author.properties.friends,0.01,0.00,0.01,5,0.02,-0.00
author.properties.status_count,0.00,0.01,0.29,5,0.01,-0.01
location.country,0.00,0.00,0.50,5,0.00,0.00
author.properties.verified,0.00,0.00,0.50,5,0.00,0.00
location.latitude,-0.00,0.00,0.86,5,0.01,-0.01

In [64]:
save_model_predictor.feature_importance(train_data, silent=True)

These features in provided data are not utilized by the predictor and will be ignored: ['properties.platform']

,importance,stddev,p_value,n,p99_high,p99_low
content.body,0.37,0.00,0.00,5,0.38,0.36
author.properties.status_count,0.03,0.01,0.00,5,0.04,0.02
author.properties.friends,0.03,0.00,0.00,5,0.03,0.02
location.latitude,0.03,0.00,0.00,5,0.03,0.02
location.longitude,0.02,0.00,0.00,5,0.02,0.01
location.country,0.00,0.00,0.50,5,0.00,0.00
author.properties.verified,-0.00,0.00,0.81,5,0.00,-0.00